#!/bin/bash

CMD_TERM="xterm -geometry 80x30 -hold -bg black -fg green -e"
traymenu qt --debug \
    --submenu "Test/sysinfo" \
        --item "disk free: $CMD_TERM df" \
        --separator \
        --item "mount: $CMD_TERM mount" \
        --submenu-end \
    --item "uptime: $CMD_TERM uptime"
